/*
 * generated by Xtext
 */
package de.sos.etj.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.sos.etj.ui.internal.ETJActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ETJExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ETJActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ETJActivator.getInstance().getInjector(ETJActivator.DE_SOS_ETJ_ETJ);
	}
	
}
