/*
 * generated by Xtext
 */
package de.sos.etj.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractETJValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(de.sos.etj.eTJ.ETJPackage.eINSTANCE);
		return result;
	}
}
