/*
 * generated by Xtext
 */
package de.sos.etj;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ETJStandaloneSetup extends ETJStandaloneSetupGenerated{

	public static void doSetup() {
		new ETJStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

