/*
 * generated by Xtext
 */
package de.sos.etj.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.common.types.xtext.ui.ITypesProposalProvider;
import org.eclipse.xtext.naming.IQualifiedNameConverter;
import org.eclipse.xtext.naming.IQualifiedNameProvider;

import de.sos.etj.ProjectQualifiedNameConverter;
import de.sos.etj.scoping.ProjectQualifiedNameProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ETJUiModule extends de.sos.etj.ui.AbstractETJUiModule {
	public ETJUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public Class<? extends ITypesProposalProvider> bindITypesProposalProvider() {
		return ETJJdtTypesProposalProvider.class;
	}
	
	
}
