/**
 * generated by Xtext
 */
package de.sos.etj.validation;

import de.sos.etj.validation.AbstractETJValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ETJValidator extends AbstractETJValidator {
}
