/*
 * generated by Xtext
 */
package de.sos.etj;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ETJUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return de.sos.etj.ui.internal.ETJActivator.getInstance().getInjector("de.sos.etj.ETJ");
	}
	
}
