/*
 * generated by Xtext
 */
package de.sos.etj.ui.contentassist

import de.sos.etj.ui.contentassist.AbstractETJProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ETJProposalProvider extends AbstractETJProposalProvider {
}
