/**
 * generated by Xtext
 */
package de.sos.etj.serializer;

import de.sos.etj.serializer.AbstractETJSemanticSequencer;

@SuppressWarnings("all")
public class ETJSemanticSequencer1 extends AbstractETJSemanticSequencer {
}
