/**
 * generated by Xtext
 */
package de.sos.etj.serializer;

import de.sos.etj.serializer.AbstractETJSyntacticSequencer;

@SuppressWarnings("all")
public class ETJSyntacticSequencer1 extends AbstractETJSyntacticSequencer {
}
