/*
 * generated by Xtext
 */
package de.sos.etj.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.sos.etj.services.ETJGrammarAccess;

public class ETJParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ETJGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.sos.etj.parser.antlr.internal.InternalETJParser createParser(XtextTokenStream stream) {
		return new de.sos.etj.parser.antlr.internal.InternalETJParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Global";
	}
	
	public ETJGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ETJGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
